openapi: 3.1.0
info:
  title: Hruych auction API
  version: 1.0.0

servers:
  - url: http://localhost:3001/api

tags:
  - name: Auctions
    description: Auctions management

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    BadRequest:
      description: Bad request - malformed syntax, invalid request structure, or missing required parameters
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    Unauthorized:
      description: Missing or invalid authentication credentials
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    Forbidden:
      description: Forbidden - authenticated but not allowed to access this resource
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    NotFound:
      description: Resource not found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'

    UnprocessableContent:
      description: Validation failed - request is syntactically correct but contains semantically invalid data
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'



  schemas:

    ProblemDetails:
      type: object
      title: Problem Details
      description: A standard error response format defined in RFC 9457.
      properties:
        type:
          type: string
          format: uri
          default: "about:blank"
          description: A URI reference that identifies the problem type.
          example: "https://example.com"
        title:
          type: string
          description: A short, human-readable summary of the problem type.
          example: "You do not have enough credit."
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server.
          example: 403
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          example: "Your current balance is 30, but the costs are 50."
        instance:
          type: string
          format: uri
          description: A URI reference that identifies the specific occurrence of the problem.
          example: "/accounts/12345/transactions/abc"

    AuctionReq:
      type: object
      required: [authorId, title, terms, image, startDateTime, endDateTime, startingBid, minBidStep]
      properties:
        authorId: { type: int, format: int64 }
        title: { type: string }
        description: { type: string }
        terms: { type: string }
        tiers:
          type: array
          items:
            $ref: '#/components/schemas/Tier'
        image: { type: string }
        startDateTime: { type: string, format: date-time }
        endDateTime: { type: string, format: date-time }
        startingBid: { type: int, format: int64 }
        minBidStep: { type: int, format: int64 }

    AuctionUpdateReq:
      type: object
      properties:
        authorId: { type: int, format: int64 }
        title: { type: string }
        description: { type: string }
        terms: { type: string }
        tiers:
          type: array
          items:
            $ref: '#/components/schemas/Tier'
        image: { type: string }
        startDateTime: { type: string, format: date-time }
        endDateTime: { type: string, format: date-time }
        startingBid: { type: int, format: int64 }
        minBidStep: { type: int, format: int64 }

    AuctionRes:
      type: object
      required: [id, author, title, terms, image, timeLeft, startingBid, minBidStep]
      properties:
        id: { type: int, format: int64, readOnly: true }
        author:
          $ref: '#/components/schemas/Author'
        title: { type: string }
        description: { type: string }
        terms: { type: string }
        tiers:
          type: array
          items:
            $ref: '#/components/schemas/Tier'
        image: { type: string }
        timeLeft: { type: string, format: date-time }
        bids:
          type: array
          items:
            $ref: '#/components/schemas/Bid'
        startingBid: { type: int, format: int64 }
        minBidStep: { type: int, format: int64 }

    Author:
      type: object
      required: [id, displayName, username, profilePic]
      properties:
        id: { type: int, format: int64, readOnly: true }
        displayName: { type: string }
        username: { type: string }
        profilePic: { type: string }

    Bid:
      type: object
      required: [id, bidder, amount]
      properties:
        id: { type: int, format: int64, readOnly: true }
        bidder:
          $ref: '#/components/schemas/Bidder'
        amount: { type: int, format: int64 }

    Bidder:
      type: object
      required: [id, displayName, username, profilePic]
      properties:
        id: { type: int, format: int64, readOnly: true }
        displayName: { type: string }
        username: { type: string }
        profilePic: { type: string }

    Tier:
      type: object
      required: [id, title, price]
      properties:
        id: { type: int, format: int64, readOnly: true }
        title: { type: string }
        price: { type: int, format: int64 }


security:
  - bearerAuth: []

paths:
  /auctions:
    get:
      summary: Get paginated auctions
      tags: [Auctions]
      security: []
      parameters:
        - name: page
          in: query
          description: Page number
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: size
          in: query
          description: Page size
          schema:
            type: integer
            minimum: 1
            default: 10
        - name: sort
          in: query
          description: Sorting criteria
          schema:
            type: string
            default: id,asc
      responses:
        '200':
          description: Ok

    post:
      summary: Create a new auction
      tags: [Auctions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuctionReq'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionRes'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /auctions/{id}:
    patch:
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: int, format: int64 }
      summary: Update auction data
      tags: [Auctions]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuctionUpdateReq'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionRes'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

